find_trending_companies:
  description: >
    Encuentra las empresas en tendencia más importantes en las noticias en {sector} buscando las últimas noticias. 
    Encuentra nuevas empresas que no has encontrado antes.
  expected_output: >
    Una lista de empresas en tendencia en {sector}
  agent:
    trending_company_finder
  output_file: output/trending_companies_{sector}.json

research_trending_companies:
  description: >
    Dada unalista de empresas en tendencia, proporciona un análisis detallado de cada empresa con un informe buscando en línea.
  expected_output: >
    Un informe que contiene un análisis detallado de cada empresas
  agent:
    financial_researcher
  context:
    - find_trending_companies
  output_file: output/research_report_{sector}.json

pick_best_company:
  description: >
    Analiza los hallazgos de la investigación y selecciona la mejor empresa para inversión.
    Envia una notificación push al usuario con la decisión y un razonamiento de 1 frase.
    Luego responde con un informe detallado sobre por que elegiste esta empresa, y cuales empresas no fueron seleccionadas y porqué no fueron elegidas.
  expected_output: >
    La empresa elegida y porqué fue elegida; las empresas que no fueron seleccionadas y porqué no fueron elegidas
  agent:
    stock_picker
  context:
    - research_trending_companies
  output_file: output/selected_company_{sector}.json