coding_task:
  description: >
    Escribe código Python para lograr este trabajo: {assignment}
  expected_output: >
    Un archivo de texto con el código que inlcuya la salida del código.
  agent: coder
  output_file: output/coder_and_output.txt